version: "3.5"
services:
  # api:
  #   build: .
  #   environment:
  #     - POSTGRES_DB=rinha
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=123
  #   ports:
  #     - "5000:5000"
  #   depends_on: 
  #     - db
    
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"